version: "3.9"
services:
  miniob-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: miniob:v1.1
    container_name: miniob
    privileged: true
    ports:
      - "10000:22"
    restart: unless-stopped
    volumes:
      - C:\Users\si_12\MyProject\Git\miniob:/root/source/miniob
